### ISSUE TITLE
Add a bit of doc on motivation for this package

### ISSUE THREAD

**Issue by rsignell-usgs** [shoyer/h5netcdf#1]
It would be great to have a bit of info on the Readme.md about the motivation for this package, and perhaps what the perceived advantages and disadvantages are (or could be) relative to other netcdf packages.

**Comment by shoyer** [comment]
This is a good idea :).

Some motivations (which I'll elaborate on in the README):

- To prove it could be done (it seemed like an obvious thing to do) and that it's not actually that hard.
- We've also seen occasional reports of better performance with h5py than netCDF4-python that I wanted to be able to verify.
- h5py seems to have thought through multi-threading pretty carefully, so this in particular seems like a case where things could make a difference. I've started to care about this because I recently hooked up a multi-threaded backend to xray ([dask](http://matthewrocklin.com/blog/work/2015/02/13/Towards-OOC-Slicing-and-Stacking/))
- It's one less massive binary dependency (netCDF C). Anecdotally, HDF5 users seem to be a unexcited switching to netCDF -- hopefully this will convince them that they are really the same thing!
- Side-stepping the netCDF C library (and Cython bindings to it) gives us an easier way to identify the source of performance issues and bugs.

**Comment by rsignell-usgs** [comment]
@shoyer, thanks for providing this!   I have a much better idea of what's going on here now.   I must agree that the HDF5 users seem to show resistance to using the NetCDF4 interface, even when they are not using any HDF5 functionality outside the NetCDF4 functionality.  So if this gets folks to write more NetCDF4-readable files, fantastic!
